 @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = Factorial.value(0);
      ;
}
 @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Factorial.value(323);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
         //
         // Number 323 is out of range [0, 20]
         //
         verifyException("org.apache.commons.numbers.combinatorics.Factorial", e);
      }
  }
 @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long long0 = Factorial.value(20);
      ;
}
 @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        Factorial.value((-2778));
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
         //
         // Number -2,778 is out of range [0, 20]
         //
         verifyException("org.apache.commons.numbers.combinatorics.Factorial", e);
      }
  }
